DROP TABLE collections;
CREATE TABLE collections ( id int NOT NULL AUTO_INCREMENT, name varchar(256), description varchar(512), date date, yr year, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE collections_projects;
CREATE TABLE collections_projects ( collection_id int NOT NULL, project_id int NOT NULL, PRIMARY KEY (collection_id, project_id), CONSTRAINT fk_coll_prog_coll FOREIGN KEY (collection_id) REFERENCES collections (id) , CONSTRAINT fk_coll_prog_prog FOREIGN KEY (project_id) REFERENCES projects (id), INDEX fk_coll_prog_prog (project_id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE customers;
CREATE TABLE customers ( id int NOT NULL AUTO_INCREMENT, name varchar(128), surname varchar(128), company varchar(256), vat varchar(128), fiscal_code varchar(128), email varchar(128), phone1 varchar(128), phone2 varchar(128), fax varchar(128), mobile varchar(128), address varchar(512), zip_code varchar(12), city varchar(128), district varchar(128), country varchar(128), vat_applied double(10,3), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into customers (id, name, surname, company, vat, fiscal_code, email, phone1, phone2, fax, mobile, address, zip_code, city, district, country, vat_applied) values (1, 'cippa', 'lippa', 'cippslipps', '', '', 'silvanoh722@gmail.com', '', '39333', '', '', '', '', '', '', '', null);
DROP TABLE model_types;
CREATE TABLE model_types ( id int NOT NULL AUTO_INCREMENT, code varchar(25), description varchar(512), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into model_types (id, code, description) values (1, 'pants', 'pantaloni uomo');
DROP TABLE model_types_sexes;
CREATE TABLE model_types_sexes ( model_type_id int NOT NULL, sex_id int NOT NULL, PRIMARY KEY (model_type_id, sex_id), CONSTRAINT fk_mod_tip_sess_mod_tipo FOREIGN KEY (model_type_id) REFERENCES model_types (id) , CONSTRAINT fk_mod_tip_sess_sess FOREIGN KEY (sex_id) REFERENCES sexes (id), INDEX fk_mod_tip_sess_sess (sex_id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into model_types_sexes (model_type_id, sex_id) values (1, 1);
DROP TABLE models;
CREATE TABLE models ( id int NOT NULL AUTO_INCREMENT, name varchar(50), description varchar(512), model_type_id int NOT NULL, sex_id int NOT NULL, image tinyblob, PRIMARY KEY (id), CONSTRAINT fk_mod_mod_tipo FOREIGN KEY (model_type_id, sex_id) REFERENCES model_types_sexes (model_type_id, sex_id), INDEX fk_mod_mod_tipo (model_type_id, sex_id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE models_projects;
CREATE TABLE models_projects ( model_id int NOT NULL, project_id int NOT NULL, PRIMARY KEY (model_id, project_id), CONSTRAINT fk_prog_mod_prog FOREIGN KEY (model_id) REFERENCES models (id) , CONSTRAINT fk_prog_mod_mod FOREIGN KEY (project_id) REFERENCES projects (id), INDEX fk_prog_mod_mod (project_id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE projects;
CREATE TABLE projects ( id int NOT NULL AUTO_INCREMENT, name varchar(256), description varchar(512), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
DROP TABLE sexes;
CREATE TABLE sexes ( id int NOT NULL AUTO_INCREMENT, code varchar(5), description varchar(512), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into sexes (id, code, description) values (1, 'M', 'men');
insert into sexes (id, code, description) values (2, 'W', 'women');
insert into sexes (id, code, description) values (3, 'U', 'unisex');
DROP TABLE suppliers;
CREATE TABLE suppliers ( id int NOT NULL AUTO_INCREMENT, name varchar(128), surname varchar(128), company varchar(256), vat varchar(128), fiscal_code varchar(128), email varchar(128), phone1 varchar(128), phone2 varchar(128), fax varchar(128), mobile varchar(128), address varchar(512), zip_code varchar(12), city varchar(128), district varchar(128), country varchar(128), PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
